#security:
#  oauth2:
#    resource:
#      tokenInfoUri: http://localhost:8080/oauth/check_token
#      preferTokenInfo: true
#    client:
#      client-id: hou
#      client-secret: 123456
#      grant-type: password
#      scope: server
#      access-token-uri: http://localhost:8080/oauth/token
#spring.redis.url=redis://localhost:6379
#spring:
#  redis:
#    url: redis://127.0.0.1:6379
#    password: 123
#    database: 0
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123
    database: 0

auth-server: http://127.0.0.1:8080/ # 认证服务器地址
#server:
#  port: 7004
security:
  oauth2:
    client:
      client-id: clientId
      client-secret: clientSecret
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
      userInfoUri: http://localhost:8080/user